#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load .profile
source $HOME/.profile

# Custom prompt
autoload -Uz promptinit
promptinit
prompt paradox

# Zplug
source $HOME/.zplug/init.zsh
autoload zplug

# fz
zplug "changyuheng/fz", defer:1
zplug "rupa/z", use:z.sh

zplug load